import type { DriveData } from "./types"

// Mock data structure for Google Drive clone
export const mockData: DriveData = {
  root: {
    type: "folder",
    name: "My Drive",
    children: ["documents", "images", "projects", "file1.txt", "presentation.pptx"],
  },
  documents: {
    type: "folder",
    name: "Documents",
    parent: "root",
    children: ["work", "personal", "resume.pdf", "notes.docx"],
  },
  work: {
    type: "folder",
    name: "Work",
    parent: "documents",
    children: ["report.docx", "data.xlsx"],
  },
  personal: {
    type: "folder",
    name: "Personal",
    parent: "documents",
    children: ["budget.xlsx", "journal.txt"],
  },
  images: {
    type: "folder",
    name: "Images",
    parent: "root",
    children: ["vacation", "profile.jpg", "screenshot.png"],
  },
  vacation: {
    type: "folder",
    name: "Vacation",
    parent: "images",
    children: ["beach.jpg", "mountain.jpg", "sunset.jpg"],
  },
  projects: {
    type: "folder",
    name: "Projects",
    parent: "root",
    children: ["website", "app", "project-plan.pdf"],
  },
  website: {
    type: "folder",
    name: "Website",
    parent: "projects",
    children: ["index.html", "styles.css", "script.js"],
  },
  app: {
    type: "folder",
    name: "App",
    parent: "projects",
    children: ["main.js", "config.json"],
  },
  "file1.txt": {
    type: "file",
    name: "file1.txt",
    parent: "root",
    size: "12 KB",
    modified: "Mar 15, 2023",
  },
  "presentation.pptx": {
    type: "file",
    name: "presentation.pptx",
    parent: "root",
    size: "2.4 MB",
    modified: "Feb 28, 2023",
  },
  "resume.pdf": {
    type: "file",
    name: "resume.pdf",
    parent: "documents",
    size: "450 KB",
    modified: "Jan 10, 2023",
  },
  "notes.docx": {
    type: "file",
    name: "notes.docx",
    parent: "documents",
    size: "35 KB",
    modified: "Mar 5, 2023",
  },
  "report.docx": {
    type: "file",
    name: "report.docx",
    parent: "work",
    size: "1.2 MB",
    modified: "Mar 12, 2023",
  },
  "data.xlsx": {
    type: "file",
    name: "data.xlsx",
    parent: "work",
    size: "890 KB",
    modified: "Mar 10, 2023",
  },
  "budget.xlsx": {
    type: "file",
    name: "budget.xlsx",
    parent: "personal",
    size: "120 KB",
    modified: "Feb 15, 2023",
  },
  "journal.txt": {
    type: "file",
    name: "journal.txt",
    parent: "personal",
    size: "45 KB",
    modified: "Mar 14, 2023",
  },
  "profile.jpg": {
    type: "file",
    name: "profile.jpg",
    parent: "images",
    size: "1.8 MB",
    modified: "Jan 5, 2023",
  },
  "screenshot.png": {
    type: "file",
    name: "screenshot.png",
    parent: "images",
    size: "950 KB",
    modified: "Mar 1, 2023",
  },
  "beach.jpg": {
    type: "file",
    name: "beach.jpg",
    parent: "vacation",
    size: "3.2 MB",
    modified: "Dec 20, 2022",
  },
  "mountain.jpg": {
    type: "file",
    name: "mountain.jpg",
    parent: "vacation",
    size: "2.8 MB",
    modified: "Dec 20, 2022",
  },
  "sunset.jpg": {
    type: "file",
    name: "sunset.jpg",
    parent: "vacation",
    size: "2.1 MB",
    modified: "Dec 21, 2022",
  },
  "project-plan.pdf": {
    type: "file",
    name: "project-plan.pdf",
    parent: "projects",
    size: "1.5 MB",
    modified: "Feb 10, 2023",
  },
  "index.html": {
    type: "file",
    name: "index.html",
    parent: "website",
    size: "15 KB",
    modified: "Mar 8, 2023",
  },
  "styles.css": {
    type: "file",
    name: "styles.css",
    parent: "website",
    size: "8 KB",
    modified: "Mar 8, 2023",
  },
  "script.js": {
    type: "file",
    name: "script.js",
    parent: "website",
    size: "12 KB",
    modified: "Mar 8, 2023",
  },
  "main.js": {
    type: "file",
    name: "main.js",
    parent: "app",
    size: "25 KB",
    modified: "Feb 25, 2023",
  },
  "config.json": {
    type: "file",
    name: "config.json",
    parent: "app",
    size: "3 KB",
    modified: "Feb 25, 2023",
  },
}

